# CI/CD Pipeline

# Test -> Build -> Deploy

# Triggers
on:
  push:
    branches:
      - "main"
      - "dev"
      - "ci"
    # we use release branch for semver/changelog updates and deploying 'rc' tags
    # thus we filter out events for branch 'release', to NOT trigger
    # avoid triggering on sem ver bump / changelog update commits
      - "!release"
      # [Git Ops]: do not trigger on Branches used only for PR labeling
      - '!board-n-release-*'
      - '!board-request-*'
    tags:
      - v*

# Note: env context only available as env vars inside 'run' blocks (ie bash script), not in 'if' (condition) blocks!

jobs:
  ### Automated TESTS ###
  test_budget_read:
    # if: always() && ( needs.pipe.outputs.OVERRIDE_UNIT_TESTS == 'true' || ( needs.pipe.outputs.OVERRIDE_UNIT_TESTS == '' && needs.pipe.result == 'success' ) )
    uses: ./.github/workflows/test-read-budget.yml

  # test:
  #   needs: pipe
  #   if: always() && ( needs.pipe.outputs.OVERRIDE_UNIT_TESTS == 'true' || ( needs.pipe.outputs.OVERRIDE_UNIT_TESTS == '' && needs.pipe.result == 'success' ) )
  #   uses: ./.github/workflows/sanity-checks.yml
  #   with:
  #     env_var_file: 'env_dev.tfvars'  # relative to ./terraform directory
  #   secrets:
  #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
